### ISSUE TITLE
AWS Credentials chain not working

### ISSUE THREAD

**Issue by azec-pdx** [keidarcy/e1s#120]
The tool fails to initialize when `~/.aws/config` file is empty and `~/.aws/credentials` file only contains profiles that work with other tooling, the example of one profile being:
```txt
...
[ProfileName_Prod_ReadOnly]
aws_access_key_id = <REDACTED>
aws_secret_access_key = <REDACTED>
aws_session_token = <REDACTED>
aws_security_token = <REDACTED>
token_expiration = 2024-01-31T02:14:57Z

...
```

Alongside this profile, the following env vars are initialized in same shell where `e1s` run is attempted:
```bash
export AWS_PROFILE=ProfileName_Prod_ReadOnly
export AWS_DEFAULT_PROFILE=ProfileName_Prod_ReadOnly
```

The attempt to run `e1s` fails with following error message:

```bash
e1s -readonly

e1s failed to start, please check your aws cli credential or permission.
operation error ECS: ListClusters, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://ecs..amazonaws.com/": Bad Request
```

**Comment by keidarcy** [comment]
Hi @azec-pdx, thank you for using `e1s`.
I investigated a little bit, StatusCode: 0 seems like [no response](https://stackoverflow.com/a/29907525).

Please upgrade to the latest version and try `tail -f /tmp/e1s-debug.log`.

I can't reproduce your aws cli authentication. Could you send me the name of the authentication or aws document link about this?
And could you tell what's the link of your other tooling, then I can check how them load aws config.

**Comment by Bexanderthebex** [comment]
@keidarcy he might be using aws cli `sso`. Link can be found [here](https://docs.aws.amazon.com/cli/latest/reference/sso/)

**Comment by keidarcy** [comment]
I upgrade all aws deps to the latest. Please upgrade e1s to >v1.0.17 and check again and reopen if it's still error.
