### ISSUE TITLE
Rendering issues after reload

### ISSUE THREAD

**Issue by ABAG603** [keidarcy/e1s#144]
Thank you for a such helpful tool! Since I started to use it, I've picked up few issues that happen after Ctrl-r is hit:

- List selection is being reset to position 0. Let's say I have 10 services and I've highlighted 4th, I'd like selection to stay on it after list is refreshed
- It seems like list is not being re-drawn until navigation keys are pressed. (press Ctrl-r, pop-up is shown that resources were reloaded but list stays exactly the same, then you press Up or Down and list is re-drawn)
- Service event view (w) being closed after Ctrl-r is pressed few times (you go back to the Services view). There is no exact number of times you need to refresh view for this to happen - sometimes it happens on a second Ctrl-r, sometimes on third...

P.S.: also +1 for the auto refresh mode (maybe at least while service is being updated)

**Comment by ABAG603** [comment]
Hi @keidarcy 

> That's true. I added a feature to persist index. Can you check with `v1.0.23`?

thanks for fixing this fast - will test ASAP
 
> > It seems like list is not being re-drawn until navigation keys are pressed. (press Ctrl-r, pop-up is shown that resources were reloaded but list stays exactly the same, then you press Up or Down and list is re-drawn)
> 
> If you mean table view. I can't reproduce this. I open two `e1s` and update one service task count in 1st `e1s`. Then go to 2nd `e1s`, press `ctrl-r` I can see the update.

What I mean is if you go to the service list, initiate service update, then wait till service to be updated (which should should at least change 'Last Deployment' field ), pressing Ctrl-R won't re-draw the list (all column values are still old) until you press Down/Up which initiates re-drawing of the table.

> > P.S.: also +1 for the auto refresh mode (maybe at least while service is being updated)
> 
> What's the usage for this? Do you open e1s and continually monitor it?

Yes, this is the case. Or at least if you updated the service, which triggered new deployment it would be useful to see deployment/service status to be updated automatically without need of pressing Ctrl-R constantly.

**Comment by ABAG603** [comment]
> 
> That's true. I added a feature to persist index. Can you check with `v1.0.23`?
> 

Tested and can confirm that selection stays after refresh.

**Comment by keidarcy** [comment]
> What I mean is if you go to the service list, initiate service update, then wait till service to be updated (which should should at least change 'Last Deployment' field ), pressing Ctrl-R won't re-draw the list (all column values are still old) until you press Down/Up which initiates re-drawing of the table.

I can see 'Last Deployment' from `completed` to `in_progress` immediately after update.

> Yes, this is the case. Or at least if you updated the service, which triggered new deployment it would be useful to see deployment/service status to be updated automatically without need of pressing Ctrl-R constantly.

I see, I would consider how to support this.

**Comment by joker22008** [comment]
https://github.com/keidarcy/e1s/issues/144#issue-2142536614

**Comment by keidarcy** [comment]
@ABAG603 Hi, can you take a look at the latest version? It should be fixed.
