### ISSUE TITLE
Unable to update task definition on services with CODE_DEPLOY deployment controller

### ISSUE THREAD

**Issue by Daivasmara** [keidarcy/e1s#145]
This is a really great tool, thank you for working on this 🙇🏻  

I only have this one issue with it where I couldn't update `desired tasks` on services with `CODE_DEPLOY` as deployment controller, I haven't look that much deeper into this but changing it from console works, so I'm guessing maybe they use AWS CodeDeploy API behind the scene to upgrade instead of normal ECS Service update, I'm wondering if `e1s` could do the same?

![Screenshot_20240220_164240](https://github.com/keidarcy/e1s/assets/40700969/4387d435-d730-4a81-b4d1-36fc94f85d4c)

**Comment by keidarcy** [comment]
@Daivasmara Hi, thank you.
I did some investigation, and when using CODE_DEPLOY can't use UpdateServiceApi to update task definition. How about only support updating desired tasks count?

**Comment by Daivasmara** [comment]
yes that sounds good for me 👍🏻

**Comment by Daivasmara** [comment]
it's working nicely! thank you for working on this 😄

![image (2)](https://github.com/keidarcy/e1s/assets/40700969/5a60da72-1f97-4136-96a6-9503b563e876)

![image (1)](https://github.com/keidarcy/e1s/assets/40700969/44cdcef9-a904-4b42-821e-a30de6f03f82)
