### ISSUE TITLE
Themes/customization support

### ISSUE THREAD

**Issue by ABAG603** [keidarcy/e1s#200]
Hi,

Can you please consider an option to allow colours customization? I use Catppuccin Mocha theme for my terminal and when I run e1s it uses much lighter background. It would be great to have an option to customize colours so they'd match terminal theme or maybe as a quick workaround just have a transparent e1s background?

**Comment by keidarcy** [comment]
Thank you! I'd like to support a custom theme feature 😄

**Comment by keidarcy** [comment]
@ABAG603 Hi, please check the latest version. It's possible to customize color theme 😌. Please let me know if you have any questions.

**Comment by ABAG603** [comment]
@keidarcy just tested and it's perfect! Thanks for putting this in quickly. The only thing I have - I was not able to figure out which colour value is used for the status bar background (where all status messages are showing up, like "Viewing clusters...", "Viewing services", etc.)

**Comment by keidarcy** [comment]
Thank you for testing. I just published a new version to fix that small debug 😄.

**Comment by ABAG603** [comment]
@keidarcy thanks! Will test as soon as it will become available in Homebrew. Btw, which colour key from config it will use?

**Comment by ABAG603** [comment]
It is perfect now. Thanks!
