### ISSUE TITLE
Option to change default sorting

### ISSUE THREAD

**Issue by ABAG603** [keidarcy/e1s#216]
Hi,

It would be great if you can allow changing default sorting (Column, Direction) per each view. Ideally, custom sorting should be saved in a state file so next time I open e1s everything's sorted how I left it.

**Comment by keidarcy** [comment]
Thank you! That's true!
A more customizable sorting is preferred. However, k9s-like sorting experience could require some hours to implement. If getting more requests about sorting, I'm open to it.
