### ISSUE TITLE
Docker image i/o timeout on api.github.com inside a private environment

### ISSUE THREAD

**Issue by SP-SuperPoney** [keidarcy/e1s#246]
Hello,

I have an issue running E1S in a docker. The docker host is a private EC2.

The following commands:
```
# docker image
docker pull ghcr.io/keidarcy/e1s:latest
# docker run with specified profile and region
docker run -it --rm -v /home/myuser/.aws:/root/.aws ghcr.io/keidarcy/e1s:latest e1s --profile myprofile --region eu-west-3
```

Generate the follwing error:
```
2024/06/11 14:12:15 Get "https://api.github.com/repos/keidarcy/e1s/releases/latest": dial tcp: lookup api.github.com on xxx.xxx.xxx.xxx:53: read udp 172.17.0.2:35787->xxx.xxx.xxx.xxx:53: i/o timeout
```

Why does the docker image is accessing github ?

**Comment by keidarcy** [comment]
Hi, many people have encountered the same issue as yours, for example: https://github.com/docker/kitematic/issues/718. It could be related to the configuration of your private
EC2 network. I don't believe it's an issue with e1s. You can test this by pulling the image locally.
Feel free to reopen if the problem still exists. Thank you.
