### ISSUE TITLE
Logs from wrong container are displayed

### ISSUE THREAD

**Issue by jlsalmon** [keidarcy/e1s#256]
Hello,

Thanks for the great tool! 

I think I might have found a bug where logs from the wrong container are being displayed. See screenshot below of logs from task `e1fd60503c464114964fd0bb89622f0e` showing the container printing its own task ID as `e9a5d8f337084920bf203b2087711fa3` which it fetched from the metadata endpoint.

I've verified by checking the CloudWatch logs that each task does indeed correctly print its own task ID, so it's not an issue with the ECS metadata endpoint or with CloudWatch. So I figure it must be e1s showing the logs from the wrong task.

Cheers!

<img width="1581" alt="Screenshot 2024-07-25 at 16 08 03" src="https://github.com/user-attachments/assets/b1030158-823a-46f1-b277-319e6eb2546b">

**Comment by keidarcy** [comment]
@jlsalmon 
Hi, thank you for using `e1s`.

The logic [here](https://github.com/keidarcy/e1s/blob/master/internal/api/logs.go#L13-L29) is getting the first log stream name by log group and getting logs by log stream which could cause your issue.

Can you help me understand whether generated log streams have any conventions? And can you show the **REDACTED** task definition?

**Comment by jlsalmon** [comment]
The relevant parts of my task definition look like this:

```
{
  "family": "my-ecs-service",
  "containerDefinitions": [
    {
      "name": "server",
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "my-ecs-service",
          "awslogs-stream-prefix": "server"
        }
      }
    }
  ]
}
```

The log group is named to match the ECS service. This config results in one log stream per container, named `server/server/{task_id}`, all inside a single log group.

So yes, I think you are right - since I have log streams for all service containers in the same log group, and since the e1s logic is only looking at the latest log stream, it's possible that we can end up looking at the wrong log stream if a different container happens to append to the log more recently.

Do you have any suggestions on how to tackle this?

**Comment by keidarcy** [comment]
@jlsalmon Thank you! No, problem. I can make `e1s` support that!

**Comment by keidarcy** [comment]
@jlsalmon Hi, please check the latest version
