### ISSUE TITLE
Keybindings and Running Tasks

### ISSUE THREAD

**Issue by dennis-tra** [keidarcy/e1s#304]
Hi there,

this tool is a game changer! Thanks so much for building open-sourcing it! I have two questions:

1. Can I remap a few keys? E.g., instead of using `ctrl`+`z` to move back, I'd rather use just `q`
2. I'm running quite a few scheduled tasks. Is it possible to view all running tasks in a cluster that are not associated with any service?

**Comment by keidarcy** [comment]
Hi, thank you.

1. e1s doesn't support custom remapping yet. I added Ctrl+Z to avoid keystroke conflicts when running it in a browser. You can use Esc instead.

2. Yes, you can do that with `n` when you are in a cluster.

**Comment by dennis-tra** [comment]
Thanks!
