### ISSUE TITLE
"Search" inside ECS logs

### ISSUE THREAD

**Issue by dhharris** [keidarcy/e1s#306]
Hi there,

Thanks so much for creating this great tool! Similarly to `k9s`, I see that you can search for strings when inside a table view using the `/` key.

<img width="712" alt="Screenshot 2024-12-17 at 14 09 45" src="https://github.com/user-attachments/assets/ba7dfc8a-9a51-477a-8dd2-f4c790909e6c" />

However, `/` key does nothing when viewing logs. I was wondering if there were any plans to support `/` key to search for matches in logs.

There's a workaround by looking at realtime log streaming `<r>` and searching using tmux, but it would be nice to do it directly in the `e1s` console.

**Comment by keidarcy** [comment]
Hi, thank you for using e1s. It may not be easy to support `k9s` like search, but I added support for open logs in the editor using `e`, so you can do searches as you like.

**Comment by dhharris** [comment]
> I added support for open logs in the editor using `e`, so you can do searches as you like.

This is great! Thanks for the quick response and new feature :)
