### ISSUE TITLE
Lacking details when using ECS over EC2 ? 

### ISSUE THREAD

**Issue by rgarrigue** [keidarcy/e1s#85]
Hi there

Gave a quick shot at e1s. It look likes what I've been looking for, except that I've few details. Maybe because we're running tasks over an EC2 ASG ? Skimming through the README I saw a focus on Fargate, might explain why <services> <tasks> and <container> are grayed out ? 

Thanks !

**Comment by keidarcy** [comment]
Hi!
It doesn't support ECS with EC2 very well.
If you can provide any terraform or cloudformation code for your usage, I'd like to support it 😃

**Comment by rgarrigue** [comment]
My usage look very much like this example https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/v5.7.3/examples/ec2-autoscaling/main.tf

**Comment by keidarcy** [comment]
@rgarrigue Thanks. Will take a look when I have spare time.

**Comment by keidarcy** [comment]
@rgarrigue Hi, I know it's been a while, I tried an EC2 on ECS myself([tf here](https://github.com/keidarcy/e1s/blob/master/tests/ec2-ecs.tf)). I found e1s is not bad for it. 
There are some missing values, it may be because EC2 on ECS does not have them, if you need any specific columns/values, I'd like to add them.

**Comment by rgarrigue** [comment]
Well I updated e1s just now & checked again, with a cluster who also run tasks on Fargate. I'm still stuck with only the ECS details, no access to the tasks. 

To give you more information, I'm Admin on the account

> arn:aws:sts::..................:assumed-role/AWSReservedSSO_AWSAdministratorAccess_8469f59b24cc0258/remy...

Starting e1s I do see the ECS clusters, but the services & tasks tabs are grayed out, even if there are tasks running

![image](https://github.com/keidarcy/e1s/assets/1872031/04f9f27d-87f7-4b8d-966c-cc11dcff147d)

I can use the shortcut b / d / f as expected. But that's it, rolled over the keyboard just in case I missed a shortcut, but nothing.

I can provide more info if you've some hidden debug switch or LOG_LEVEL, just tell me what to do

**Comment by rgarrigue** [comment]
I realized there's a messup with my PATH and an older binary, the above screen is running 1.0.7. Fixed it, with 1.0.29 I've an explicit
                                                     💥 no valid service                                                     

We don't use service. TasksDefinition are created either in the code or via Terraform, and the code run Tasks. I guess the fix I need is being able to see the Tasks even if not attached to a service. Same for containers.

**Comment by keidarcy** [comment]
@rgarrigue 
Oh, that's expected. I didn't know it's possible to run a task without a service.

Current implementation is cluster => service => task => container.

Could you help me understand how to set it up with [terraform here](https://github.com/keidarcy/e1s/blob/master/tests/ec2-ecs.tf), I'd like to support it!

**Comment by rgarrigue** [comment]
Hmm since this is part of our app code, it'd take time to extrat / adapt to give you a terraform example

Instead here's a script I made to quickly spin up stuff a bit like our app (& try out permissions afterward). I won't guarantee it works 100%, there were some hardcoded stuff that I twisted during the test, the 1st half of the script was broken while working on the 2nd half, then I sanitized a couple of info before putting it here. 

Nevertheless the "run" command is what you're looking for, starting one time task based on a TD without service.

I'd suggest that you allow one to navigate to <services> <tasks> & <containers> tabs given they select a cluster in the 1st tab, would prevent confusion
Also, allowing someone to browse the TaskDefinitions without going through services / describe the TD for this service  could be interesting for my "no service" usage.

```bash
#!/usr/bin/env bash

OPERATION=${1:-"create"}
CLUSTER=${2:-"arn:aws:ecs:eu-north-1:____________:cluster/____-development-data-ecs"}
PROVIDER=${3:-"EC2"}
ROLE=${4:-"arn:aws:iam::____________:role/____-development-data-ecs"}
TD="arn:aws:ecs:eu-north-1:____________:task-definition/ecs-test-td:5"


if [ "$OPERATION" = "status" ] ; then
    SV_ARN=$(aws ecs list-services --cluster "$CLUSTER" | jq -r '.serviceArns[] | select(.|contains("ecs-test-service"))')
    if [ "$SV_ARN" != "" ] ; then
        aws ecs describe-services --cluster "$CLUSTER" --services "$SV_ARN" | jq -r '.services[0].events[]|.message'
    fi
fi



if [ "$OPERATION" = "list" ] ; then
    echo "Task definitions:"
    aws ecs list-task-definitions | jq -r '"    " + .taskDefinitionArns[]'
    echo "Services:"
    aws ecs list-services --cluster "$CLUSTER" | jq -r '"    " + .serviceArns[]'
    echo "Container instances:"
    aws ecs list-container-instances --cluster "$CLUSTER" | jq -r '"    " + .containerInstanceArns[]'
    echo "Tasks:"
    aws ecs list-tasks --cluster "$CLUSTER" | jq -r '"    " + .taskArns[]'
fi



if [ "$OPERATION" = "run" ] ; then
  echo "Run task"
  SUBNETS=$(aws ec2 describe-subnets | jq -r '.Subnets[]|select(.Tags[].Value|contains("public"))|.SubnetId' | sort -u | tr '\n' ',' | sed 's/,$//')
  SG=$(aws ec2 describe-security-groups | jq -r '.SecurityGroups[] | select(.GroupName | contains("ecs") ) | .GroupId')
  aws ecs run-task \
    --cluster $CLUSTER \
    --task-definition $TD \
    --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS], securityGroups=[$SG], assignPublicIp=ENABLED}" 
    # --overrides '{"containerOverrides":[{"name":"task-worker","command":["bash", "-c", "apt-get update &>/dev/null ; apt-get install -y awscli &>/dev/null ; aws secretsmanager list-secrets --query Name ; aws secretsmanager get-secret-value --secret-id prod/____omate/superadmin --query SecretString --output text"]}]}'
fi
```

**Comment by keidarcy** [comment]
Thank you! I didn't know that! I understand how it works, and will support it.

**Comment by keidarcy** [comment]
@rgarrigue Hi, can you check the latest version? If you press 'n' in clusters, it should go to tasks 😄

**Comment by rgarrigue** [comment]
It works. About the "n" shortcut, doesn't feel intuitive, I naturally tried "tab", "enter", "right arrow" to move between clusters / tasks / containers

**Comment by keidarcy** [comment]
Thanks!
> About the "n" shortcut, doesn't feel intuitive, I naturally tried "tab", "enter", "right arrow" to move between clusters / tasks / containers

That's true. Because they are used for default movement - `clusters` <=> `services`. And `enter` is impossible to determine, from `clusters` to `services` or `tasks`.

Since `e1s` seems to work for viewing tasks in the cluster. I'll close this issue. If we discover any problems in the future, I'm open to it.
