### ISSUE TITLE
View service/task logs

### ISSUE THREAD

**Issue by tmeijn** [keidarcy/e1s#88]
Just discovered this tool and it looks awesome!

I'd like to view the logs of a service/task, just like in k9s 😄 

Maybe some like [Cloudwatch Logs Live Tail](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatchLogs_LiveTail.html) can be used for this?

AWS CLI ref: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/tail.html

**Comment by tmeijn** [comment]
Was looking into this a bit more, but this would really only be possible if the LogDriver is `awslogs`. So the logic would need to:

1. check if the LogDriver is set as `awslogs`, otherwise we cannot provide logs.
2. get the `awslogs-group` and `awslogs-stream-prefix` from the `options` object
3. Open a livetail stream with these options

Asked GPT for the logic in Bash, for reference: https://chat.openai.com/share/28d42258-2285-4462-9ee3-1aadb05f6d91

**Comment by keidarcy** [comment]
@tmeijn
Hi, thank you for your investigation. I added in `v1.0.11`.
Could you check does it fits your needs? 😃

**Comment by tmeijn** [comment]
Hey @keidarcy, thanks so much for getting this in, this looks already really awesome!

I think I did discover a bug: as you can see in the screenshot below, the logs repeat themself one time. Not a big one, but maybe there is some double fetching going on? 🤔 

![image](https://github.com/keidarcy/e1s/assets/17970041/732b5be0-062f-45d8-b287-022ba6a7a018)

---

A suggestion: since this tool looks a bit like `k9s`, maybe an idea to keep parity between them in regards to the shortcuts used? Now the `logs` function is accessed with `o`, while in `k9s` it is `l`. In `e1s` this shortcut is undocumented, but does seem to have the same function as `<enter>`.

---

A possible improvement: would it be easy to make the new reload functionality also work in the log view?

Again, thanks so much for putting this in ❤️ .

**Comment by keidarcy** [comment]
Hi, @tmeijn . Thank you for using `e1s`.

> double health check logs

You can see there are different IPs. They are from different containers. I guess your task definition has multiple containers healthcheck setup.


> keybind

I want to keep vim keybind to move back and forth. If I hear more people think the same, I may change.

> reload in log view

I'm considering to add it.

**Comment by tmeijn** [comment]
@keidarcy

> You can see there are different IPs. They are from different containers. I guess your task definition has multiple containers healthcheck setup.

Sorry, should've been more clear, I mean the whole log repeats: if you look at the screenshot again you can see two times `no-op change`. If you look at the timestamps you can see they are exactly the same and if you both following them down you see that the log lines are repeating themselves with the same timestamp.

**Comment by tmeijn** [comment]
Hey @keidarcy 

> thinking instead of fetching by API just show aws logs tail output

Yeah that was my original proposal to use the `aws logs tail` equivalent in the SDK. If this is workable it would the same experience as `k9s` where the logs also stream in live.

> But it doesn't support multiple log groups.

`e1s` provides logging and the task level and individual container level right? So the only time when some multiple log groups would be needed is if someone decides to put multiple container definitions into a task AND decides to assign these containers different log groups. This does not seem logical to me and would IMHO justify to just not support this.

**Comment by keidarcy** [comment]
Hi @tmeijn I added `r` in log view for realtime log in `v1.0.14` 😄

**Comment by tmeijn** [comment]
Haha, you just decided to support both, really awesome! 💪🏾 

There really isn't a place to say this so I'm doing it here: I'm planning a migration **off** Kubernetes to ECS and this tool being available as an "equivalent" (not yet, but pretty close already!) to `k9s` was one of the deciding factors as we use `k9s` a lot. I also made sure you got a shout out at [Cloud Posse Office Hours](https://youtu.be/of-SvGfxJ2o?si=sySPEL0CPkeKRB2Q&t=1485). Really appreciate the work you've done here.

Alright, that's it, if I have any other issues I'll open a new one 😄 .

**Comment by keidarcy** [comment]
Hey, @tmeijn! Thanks a lot. I guess that's why it's getting some attention 😂

I'm glad that this project can help you a bit.
