### ISSUE TITLE
Add options to reload and/or auto-refresh

### ISSUE THREAD

**Issue by tmeijn** [keidarcy/e1s#89]
In `k9s` the UI gets automatically refreshed and you can force a reload with `<ctrl>+r`. In `e1s` this is not the case and forcing a reload is also not supported. I'd like at least to have the ability to force a reload, with a further enhancement being the auto refresh.

**Comment by tmeijn** [comment]
Thanks again, @keidarcy!

Works great! Only minor suggestion, coming from the previous comment, is that manual refresh in `k9s` is `<ctrl> +r` and might be an idea to let this be the same. I totally understand if parity with `k9s` is not the goal here 😄 .

**Comment by keidarcy** [comment]
makes sense, will change it in the next version 😄
